[unix_http_server]
file=/run/supervisor.sock

[supervisord]
nodaemon=true
logfile=/var/log/pc-free/supervisord.log
pidfile=/run/pc-free-supervisord.pid
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[include]
files=/etc/supervisor/conf.d/*.conf
